version: '3.9'
services:
  webserver:
    container_name: web_server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db
    networks:
      - mynetwork
  db:
    image: postgres:13
    container_name: gatherly_db
    environment:
      POSTGRES_DB: gathery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mynetwork
volumes:
  postgres_data:
networks:
  mynetwork: